version: 2
jobs:
  node:
    working_directory: ~/react-native-radar
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run: npm install
      - run: npm install -g typescript
      - run:
          name: Test
          command: |
            mkdir -p test-results/jest
            npm run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - run:
          name: Type-check
          command: npm run build-all
      - persist_to_workspace:
          root: ~/react-native-radar
          paths:
            - android
            - ios
            - README.md
            - react-native-radar.podspec
            - dist
            - app.plugin.js
            - plugin/build
            - example
            - package.json
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  android:
    working_directory: ~/react-native-radar/example
    docker:
      - image: cimg/android:2024.01.1-browsers
    steps:
      - attach_workspace:
          at: ~/react-native-radar
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Radar from local path
          command: npm run install-radar-rebuild
      - run: sudo yarn global add react-native
      - run:
          name: Install Ninja
          command: sudo apt-get update && sudo apt-get install -y ninja-build
      - run: chown -R $USER:$USER android
      - run: cd android && ./gradlew 
  ios:
    macos:
      xcode: "15.3.0"
    working_directory: ~/react-native-radar/example
    steps:
      - attach_workspace:
          at: ~/react-native-radar
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v18
            nvm alias default 18.19.1

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Radar from local path
          command: npm run install-radar-rebuild
      - run: react-native run-ios

workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
