version: 2
jobs:
  node:
    working_directory: ~/react-native-radar
    docker:
      - image: cimg/node:18.0
    steps:
      - checkout
      - run: npm install
      - run: npm install -g typescript
      - run:
          name: Test
          command: |
            mkdir -p test-results/jest
            npm run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - run:
          name: Type-check
          command: npm run prepare
      - persist_to_workspace:
          root: ~/react-native-radar
          paths:
            - android
            - ios
            - README.md
            - react-native-radar.podspec
            - dist
            - app.plugin.js
            - plugin/build
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  android:
    working_directory: ~/react-native-radar/example
    docker:
      - image: cimg/android:2023.02.1-browsers
    steps:
      - attach_workspace:
          at: ~/react-native-radar
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Radar from local path
          command: npm run install-radar-rebuild -y
      - run:
          name: Install Expo CLI
          command: npm install -g expo-cli
      - run:
          name: Run Expo App
          command: npx expo run:android
  ios:
    macos:
      xcode: "13.4.1"
    working_directory: ~/react-native-radar/example
    steps:
      - checkout:
          path: ~/react-native-radar
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v18
            nvm alias default 18.19.1

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install -g typescript
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Radar from local path
          command: npm run install-radar
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Install Expo CLI
          command: npm install -g expo-cli
      - run:
          name: Install CocoaPods dependencies
          command: |
            npx pod-install
      - run:
          name: Run Expo App
          command: npx expo run:ios
workflows:
  version: 2
  node-android-ios:
    jobs:
      - node
      - android:
          requires:
            - node
      - ios:
          requires:
            - node
